- src/wsm/Podfile
- src/wsm/Podfile.lock
- src/wsm/wsm.xcodeproj/project.pbxproj
- src/wsm/wsm/Base.lproj/Main.storyboard
- src/wsm/wsm/Info.plist
- src/wsm/wsm/api/API.swift
- src/wsm/wsm/api/ApiHelper.swift
- src/wsm/wsm/api/Provider/LoginProvider.swift
- src/wsm/wsm/api/Provider/UserProvider.swift
- src/wsm/wsm/api/WsmAccessTokenPlugin.swift
- src/wsm/wsm/model/User.swift
- src/wsm/wsm/model/UserProfile.swift
- src/wsm/wsm/viewcontrollers/Login/LoginControllerType.swift
- src/wsm/wsm/viewcontrollers/Login/LoginViewController.swift
- update lại 1 số function trong framework cho phù hợp với project
- Ui Login: inprogress
- tạo function login theo framework chạy thành công
- thêm WSM-LOCALE &  WSM-AUTH-TOKEN vào request header
- redmine: https://dev.framgia.com/redmine/issues/137818
> Investigate framework

- src/wsm/wsm.xcodeproj/project.pbxproj
- src/wsm/wsm/AppDelegate.swift
- src/wsm/wsm/Base.lproj/LaunchScreen.storyboard
- src/wsm/wsm/Base.lproj/Main.storyboard
- src/wsm/wsm/Info.plist
- src/wsm/wsm/MenuEnum.swift
- src/wsm/wsm/api/Provider/UserProvider.swift
- src/wsm/wsm/api/WsmAccessTokenPlugin.swift
- src/wsm/wsm/base/BaseViewController.swift
- src/wsm/wsm/extensions/Extension.swift
- src/wsm/wsm/extensions/UIColor.swift
- src/wsm/wsm/interfaces/LeftMenuHeaderCell.xib
- src/wsm/wsm/interfaces/LeftMenuSectionCell.xib
- src/wsm/wsm/interfaces/TimeSheetViewController.xib
- src/wsm/wsm/interfaces/UserInfoViewController.xib
- src/wsm/wsm/model/UserProfile.swift
- src/wsm/wsm/viewcontrollers/Home/HomeControllerType.swift
- src/wsm/wsm/viewcontrollers/Home/HomeViewController.swift
- src/wsm/wsm/viewcontrollers/Home/MainViewController.swift
- src/wsm/wsm/viewcontrollers/LeftMenuCell.swift
- src/wsm/wsm/viewcontrollers/LeftMenuHeaderCell.swift
- src/wsm/wsm/viewcontrollers/LeftMenuSectionCell.swift
- src/wsm/wsm/viewcontrollers/LeftMenuViewController.swift
- src/wsm/wsm/viewcontrollers/Login/LoginViewController.swift
- src/wsm/wsm/viewcontrollers/NavigationController.swift
- src/wsm/wsm/viewcontrollers/TimeSheetViewController.swift
- src/wsm/wsm/viewcontrollers/TimeSheetViewController.xib
- src/wsm/wsm/viewcontrollers/UserInfoViewController.swift
- src/wsm/wsm/viewcontrollers/UserInfoViewController.xib
Progress : 60%
Redmine: https://dev.framgia.com/redmine/issues/138044
Effect: None
> Main page Ui (navigator + header + side menu)

- src/wsm/wsm/Base.lproj/Main.storyboard
- src/wsm/wsm/base/BaseViewController.swift
- src/wsm/wsm/extensions/UITextField.swift
- src/wsm/wsm/viewcontrollers/Login/LoginViewController.swift
redmine: https://dev.framgia.com/redmine/issues/138262
effect: none
> Task #138262 [Sprint 1] Login UI

- src/wsm/wsm.xcodeproj/project.pbxproj
- src/wsm/wsm/Base.lproj/Main.storyboard
- src/wsm/wsm/api/API.swift
- src/wsm/wsm/api/ApiInputModels/RequestOtApiInputModel.swift
- src/wsm/wsm/api/CreateRequestOtApiOutModel.swift
- src/wsm/wsm/api/Provider/RequestOtProvider.swift
- src/wsm/wsm/base/BaseModel.swift
- src/wsm/wsm/extensions/Date.swift
- src/wsm/wsm/extensions/UIImageView.swift
- src/wsm/wsm/interfaces/LeftMenuHeaderCell.xib
- src/wsm/wsm/localization/en.lproj/Localizable.strings
- src/wsm/wsm/localization/vi.lproj/Localizable.strings
- src/wsm/wsm/model/RequestOtModel.swift
- src/wsm/wsm/model/UserGroup.swift
- src/wsm/wsm/model/UserProfileModel.swift
- src/wsm/wsm/model/UserWorkSpace.swift
- src/wsm/wsm/services/UserServices.swift
- src/wsm/wsm/viewcontrollers/ConfirmCreateRequestOtViewControllerType.swift
- src/wsm/wsm/viewcontrollers/LeftMenuHeaderCell.swift
- src/wsm/wsm/viewcontrollers/LeftMenuViewController.swift
- src/wsm/wsm/viewcontrollers/Login/LoginControllerType.swift
- src/wsm/wsm/viewcontrollers/Login/LoginViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOt/ConfirmCreateRequestOtViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOt/CreateRequestOtViewController.swift
UI screen confirm create request OT
redmine: https://dev.framgia.com/redmine/issues/139155
effect: none
> Task #139155 [Sprint 2] UI screen confirm create request OT

- src/wsm/Podfile
- src/wsm/Podfile.lock
- src/wsm/wsm.xcodeproj/project.pbxproj
- src/wsm/wsm/Base.lproj/Main.storyboard
- src/wsm/wsm/base/WsmTextField.swift
- src/wsm/wsm/extensions/UITextField.swift
- src/wsm/wsm/viewcontrollers/RequestOt/CreateRequestOtViewController.swift
Thay đổi thư viện để textbox giống với android hơn
redmine: https://dev.framgia.com/redmine/issues/139155
effect: none
> Task #139155 [Sprint 2] Create Request OT Logic

- src/wsm/wsm.xcodeproj/project.pbxproj
- src/wsm/wsm/Base.lproj/Main.storyboard
- src/wsm/wsm/base/RequestBaseViewController.swift
- src/wsm/wsm/viewcontrollers/LeftMenuViewController.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/CreateRequestLeaveViewController.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/ListRequestLeaveViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOt/CreateRequestOtViewController.swift
Init list & create screens
Create base viewcontroller
redmine: https://dev.framgia.com/redmine/issues/139562
effect: none
> Task #139562 [Sprint 2]Create Request Leave UI

- src/wsm/wsm.xcodeproj/project.pbxproj
- src/wsm/wsm/Base.lproj/Main.storyboard
- src/wsm/wsm/api/API.swift
- src/wsm/wsm/api/ApiInputModels/RequestLeaveApiInputModel.swift
- src/wsm/wsm/api/ApiInputModels/RequestOtApiInputModel.swift
- src/wsm/wsm/api/ApiOutputModels/CreateRequestLeaveApiOutModel.swift
- src/wsm/wsm/api/Provider/RequestLeaveProvider.swift
- src/wsm/wsm/api/Provider/RequestOtProvider.swift
- src/wsm/wsm/base/RequestBaseViewController.swift
- src/wsm/wsm/enums/LeaveType.swift
- src/wsm/wsm/model/LeaveTypeModel.swift
- src/wsm/wsm/model/RequestLeaveModel.swift
- src/wsm/wsm/services/UserServices.swift
- src/wsm/wsm/viewcontrollers/ConfirmCreateRequestLeaveViewController.swift
- src/wsm/wsm/viewcontrollers/ConfirmCreateRequestLeaveViewControllerType.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/CreateRequestLeaveViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOt/ConfirmCreateRequestCell.swift
- src/wsm/wsm/viewcontrollers/RequestOt/ConfirmCreateRequestOtViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOt/CreateRequestOtViewController.swift
redmine: https://dev.framgia.com/redmine/issues/139562
effect: none
> Request Leave UI

- src/wsm/wsm.xcodeproj/project.pbxproj
- src/wsm/wsm/Base.lproj/Main.storyboard
- src/wsm/wsm/api/Base/API.swift
- src/wsm/wsm/api/RequestLeaveApi/ListRequestLeavesApiOutModel.swift
- src/wsm/wsm/api/RequestLeaveApi/RequestLeaveApiInputModel.swift
- src/wsm/wsm/api/RequestLeaveApi/RequestLeaveProvider.swift
- src/wsm/wsm/base/WsmTextField.swift
- src/wsm/wsm/enums/RequestStatus.swift
- src/wsm/wsm/model/CompensationAttribute.swift
- src/wsm/wsm/model/RequestLeaveModel.swift
- src/wsm/wsm/services/UserServices.swift
- src/wsm/wsm/utils/AppConstant.swift
- src/wsm/wsm/viewcontrollers/ConfirmCreateRequestLeaveViewControllerType.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/ListRequestLeaveViewController.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/RequestLeaveCell.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/RequestLeaveCell.xib
status: in progress
redmine: https://dev.framgia.com/redmine/issues/140709
effect: none
> Task #140709 [Sprint 2] List Request Leave UI

- src/wsm/wsm.xcodeproj/project.pbxproj
- src/wsm/wsm/Base.lproj/Main.storyboard
- src/wsm/wsm/api/Base/API.swift
- src/wsm/wsm/api/RequestLeaveApi/RequestLeaveProvider.swift
- src/wsm/wsm/enums/RequestStatus.swift
- src/wsm/wsm/extensions/UIColor.swift
- src/wsm/wsm/extensions/UIViewController.swift
- src/wsm/wsm/localization/en.lproj/Localizable.strings
- src/wsm/wsm/localization/vi.lproj/Localizable.strings
- src/wsm/wsm/model/RequestLeaveModel.swift
- src/wsm/wsm/utils/AlertHelper.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/ListRequestLeaveViewController.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/RequestFilterView.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/RequestLeaveCell.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/RequestLeaveDetailViewController.swift
redmine: https://dev.framgia.com/redmine/issues/141146
effect: none
> Task #141146 [Sprint 4] Delete Request Leave Logic

- src/wsm/wsm/viewcontrollers/RequestOt/CreateRequestOtViewController.swift
update validate logic
redmine: https://dev.framgia.com/redmine/issues/139155
effect: none
> Create Request OT Logic

- src/wsm/Podfile.lock
- src/wsm/wsm.xcodeproj/project.pbxproj
- src/wsm/wsm/Base.lproj/Main.storyboard
- src/wsm/wsm/api/RequestOtApi/RequestOTProvider.swift
- src/wsm/wsm/viewcontrollers/RequestOt/ListRequestOtViewController.swift
- Filter Request OT UI + Logic
- Redmine: https://dev.framgia.com/redmine/issues/141876
- Effect: None
> Task #141876 [Sprint 5] Filter Request OT Logic

- src/wsm/wsm.xcodeproj/project.pbxproj
- src/wsm/wsm/Base.lproj/Main.storyboard
- src/wsm/wsm/extensions/Date.swift
- src/wsm/wsm/model/RequestOtModel.swift
- src/wsm/wsm/utils/AppConstant.swift
- src/wsm/wsm/viewcontrollers/RequestOt/ListRequestOtViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOt/OtRequestDetailViewController.swift
- OT Request Detail 
- Redmine: https://dev.framgia.com/redmine/issues/142294
- Effect: None
> [Task #142294] Feature OT Request detail

- src/wsm/wsm/Base.lproj/Main.storyboard
- src/wsm/wsm/api/RequestOtApi/RequestOTProvider.swift
- src/wsm/wsm/api/RequestOtApi/RequestOtApiInputModel.swift
- src/wsm/wsm/base/RequestBaseViewController.swift
- src/wsm/wsm/model/RequestOtModel.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/ConfirmCreateRequestLeaveViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOt/ConfirmCreateRequestOtViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOt/CreateRequestOtViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOt/ListRequestOtViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOt/OtRequestDetailViewController.swift
- Update/ Delete OT Request
- Redmine: https://dev.framgia.com/redmine/issues/142657
- Effect: Create Ot Request, List Request
> [Sprint 5][Task #142657]Feature update delete OT request

- src/wsm/Podfile
- src/wsm/Podfile.lock
- src/wsm/wsm.xcodeproj/project.pbxproj
- src/wsm/wsm/Base.lproj/Main.storyboard
- src/wsm/wsm/api/Base/API.swift
- src/wsm/wsm/api/Base/MoyaProvider+Promise.swift
- src/wsm/wsm/api/Base/Response+ObjectMapper.swift
- src/wsm/wsm/api/RequestOffApi/RequestOffApiInputModel.swift
- src/wsm/wsm/api/RequestOffApi/RequestOffProvider.swift
- src/wsm/wsm/base/WsmTextField.swift
- src/wsm/wsm/enums/DateOffType.swift
- src/wsm/wsm/interfaces/RequestTextFieldCell.xib
- src/wsm/wsm/localization/en.lproj/Localizable.strings
- src/wsm/wsm/localization/vi.lproj/Localizable.strings
- src/wsm/wsm/model/ConfirmRequestItem.swift
- src/wsm/wsm/model/DayOffSettingModel.swift
- src/wsm/wsm/model/RequestDayOffModel.swift
- src/wsm/wsm/utils/AlertHelper.swift
- src/wsm/wsm/utils/AppConstant.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/ConfirmCreateRequestLeaveViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOff/ConfirmCreateRequestOffCell.swift
- src/wsm/wsm/viewcontrollers/RequestOff/ConfirmCreateRequestOffDayOffSettingCell.swift
- src/wsm/wsm/viewcontrollers/RequestOff/ConfirmCreateRequestOffViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOff/CreateRequestOffTimeCell.swift
- src/wsm/wsm/viewcontrollers/RequestOff/CreateRequestOffViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOff/CreateRequestOffViewControllerType.swift
- src/wsm/wsm/viewcontrollers/RequestOff/ListRequestOffViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOt/ConfirmCreateRequestOtViewController.swift
- Redmine (vì là 2 task liên quan nên có 2 link redmine): https://dev.framgia.com/redmine/issues/141698, https://dev.framgia.com/redmine/issues/141699
- Finish logic tạo request off
- Finish màn hình confirm
- Sửa logic chỗ tạo request để support việc tạo 1 request có nhiều loại nghỉ (nghỉ có lương, nghỉ không lương,...)
- Lưu thành công 1 request có nhiều loại nghỉ
- Update lại tầng API để hiển thị được format json với lỗi trả về là dạng array
> [task/141698] Create Request Off Confirm UI

- src/wsm/Podfile
- src/wsm/Podfile.lock
- src/wsm/wsm.xcodeproj/project.pbxproj
- src/wsm/wsm/Base.lproj/Main.storyboard
- src/wsm/wsm/api/Base/Plugins/WsmAccessTokenPlugin.swift
- src/wsm/wsm/api/NotificationApi/ListNotificationOuputApiModel.swift
- src/wsm/wsm/api/NotificationApi/NotificationProvider.swift
- src/wsm/wsm/api/UserApi/UserProvider.swift
- src/wsm/wsm/base/BaseViewController.swift
- src/wsm/wsm/enums/NotificationOwnerType.swift
- src/wsm/wsm/enums/NotificationTrackableType.swift
- src/wsm/wsm/model/NotificationModel.swift
- src/wsm/wsm/services/UserServices.swift
- src/wsm/wsm/viewcontrollers/Home/MainViewController.swift
- src/wsm/wsm/viewcontrollers/Login/LoginControllerType.swift
- src/wsm/wsm/viewcontrollers/Notification/NotificationCell.swift
- src/wsm/wsm/viewcontrollers/Notification/NotificationViewController.swift
UI: finish
Logic: 50%
redmine: https://dev.framgia.com/redmine/issues/143251
effect: none
> Task #143251 [Sprint 6] NotificationUI & logic

- src/wsm/wsm/viewcontrollers/RequestLeave/CreateRequestLeaveViewController.swift
- src/wsm/wsm/viewcontrollers/TimeSheet/TimeSheetViewController.swift
redmine: 
- https://dev.framgia.com/redmine/issues/143664
- https://dev.framgia.com/redmine/issues/143327
effect: none
> Bug #143327 & #143664

- src/wsm/wsm/api/Base/API.swift
- src/wsm/wsm/utils/AlertHelper.swift
- If Unauthorized show dialog, click button on dialog go to Login Screen
- Redmine: https://dev.framgia.com/redmine/issues/143718
- Effect: None
> [Task #143718] Handle Unauthorized

- src/wsm/wsm/customviews/MonthYearPickerView.swift
- src/wsm/wsm/model/WorkSpaceShift.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/CreateRequestLeaveViewController.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/RequestFilterView.swift
progress: finish:
effect: none
redmine:
- https://dev.framgia.com/redmine/issues/143805
- https://dev.framgia.com/redmine/issues/143707
- https://dev.framgia.com/redmine/issues/143680
> Fix Bug #143805, #143707, #143680

- src/wsm/wsm/model/WorkSpaceShift.swift
- src/wsm/wsm/utils/AppConstant.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/CreateRequestLeaveViewController.swift
effect: none
redmine: https://dev.framgia.com/redmine/issues/143863
> Bug #143863

- src/wsm/wsm/viewcontrollers/TimeSheet/TimeSheetViewController.swift
Fixed issuse: https://www.chatwork.com/#!rid75951589-975669407319609344
> [task/138772] Update timesheet logic

- src/wsm/Podfile
- src/wsm/Podfile.lock
- src/wsm/wsm.xcodeproj/project.pbxproj
- src/wsm/wsm/Base.lproj/Main.storyboard
- src/wsm/wsm/api/Statistic/StatisticApiOutputModel.swift
- src/wsm/wsm/api/Statistic/StatisticProvider.swift
- src/wsm/wsm/interfaces/StatictisHeaderView.xib
- src/wsm/wsm/model/ConfirmRequestItem.swift
- src/wsm/wsm/model/StatisticOfMonthModel.swift
- src/wsm/wsm/model/StatisticOfYearModel.swift
- src/wsm/wsm/viewcontrollers/Profile/ProfileDetailViewController.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/ConfirmCreateRequestLeaveViewController.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/RequestLeaveDetailViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOff/ConfirmCreateRequestOffCell.swift
- src/wsm/wsm/viewcontrollers/RequestOff/ConfirmCreateRequestOffDayOffSettingCell.swift
- src/wsm/wsm/viewcontrollers/RequestOff/ConfirmCreateRequestOffViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOff/RequestOffDetailViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOt/ConfirmCreateRequestCell.swift
- src/wsm/wsm/viewcontrollers/RequestOt/ConfirmCreateRequestOtViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOt/OtRequestDetailViewController.swift
- src/wsm/wsm/viewcontrollers/SideMenu/LeftMenuViewController.swift
- src/wsm/wsm/viewcontrollers/Statistic/StatictisHeaderView.swift
- src/wsm/wsm/viewcontrollers/Statistic/StatisticCell.swift
- src/wsm/wsm/viewcontrollers/Statistic/StatisticGroupCell.swift
- src/wsm/wsm/viewcontrollers/Statistic/StatisticSectionHeaderView.swift
- src/wsm/wsm/viewcontrollers/Statistic/StatisticSectionHeaderView.xib
- src/wsm/wsm/viewcontrollers/Statistic/StatisticViewController.swift
effect: none
redmine: https://dev.framgia.com/redmine/issues/143266
> Task #143266 [Sprint 6] Statictis user

- src/wsm/wsm.xcodeproj/project.pbxproj
- src/wsm/wsm/Info.plist
- src/wsm/wsm/interfaces/RequestOTCell.xib
- src/wsm/wsm/interfaces/RequestTextFieldCell.xib
- src/wsm/wsm/viewcontrollers/ManageRequestListViewController.swift
- src/wsm/wsm/viewcontrollers/ManageRequestListViewController.xib
- src/wsm/wsm/viewcontrollers/ManageRequestTableViewCell.swift
- src/wsm/wsm/viewcontrollers/ManageRequestTableViewCell.xib
- src/wsm/wsm/viewcontrollers/RequestType.swift
- src/wsm/wsm/viewcontrollers/SideMenu/LeftMenuViewController.swift
- Detail: manage request list UI
- Redmine: https://dev.framgia.com/redmine/issues/144475
- Effect: None
> [Sprint 7][Task #144475] Feature manage request list UI

- src/wsm/wsm.xcodeproj/project.pbxproj
- src/wsm/wsm/api/ManageLeaveRequestApiOutputModel.swift
- src/wsm/wsm/api/ManageOffRequestApiOutputModel.swift
- src/wsm/wsm/api/ManageOvertimeRequestApiOutputModel.swift
- src/wsm/wsm/api/ManageRequestApiInputModel.swift
- src/wsm/wsm/api/ManageRequestProvider.swift
- src/wsm/wsm/viewcontrollers/ManageRequestListViewController.swift
- src/wsm/wsm/viewcontrollers/ManageRequestTableViewCell.xib
- Call API fill data into list
- Accept/ Reject member requests
- Redmine: https://dev.framgia.com/redmine/issues/144646
- Effect: 3 screen manage request
> task/#144646 Feature manage list logic P1

- src/wsm/wsm/api/ManageRequestProvider.swift
- src/wsm/wsm/localization/en.lproj/Localizable.strings
- src/wsm/wsm/localization/vi.lproj/Localizable.strings
- src/wsm/wsm/model/RequestDayOffModel.swift
- src/wsm/wsm/model/RequestOtModel.swift
- src/wsm/wsm/utils/AppConstant.swift
- src/wsm/wsm/viewcontrollers/ManageRequestListViewController.swift
- src/wsm/wsm/viewcontrollers/ManageRequestTableViewCell.swift
- src/wsm/wsm/viewcontrollers/ManageRequestTableViewCell.xib
- Handle fill data into TableView
- Accept/ Reject member requests
- Redmine: https://dev.framgia.com/redmine/issues/144646
- Effect: 3 screen manage request
> logic list manage request

- src/wsm/wsm.xcodeproj/project.pbxproj
- src/wsm/wsm/AppDelegate.swift
- src/wsm/wsm/GoogleService-Info.plist
- src/wsm/wsm/Info.plist
- src/wsm/wsm/api/LoginApi/LoginProvider.swift
- src/wsm/wsm/wsm.entitlements
https://dev.framgia.com/redmine/issues/147930
- Configure to receive remote notifications with Firebase.
- Change app id to com.framgia.wsm
- Add FCM token when logging in.
> [Task][#147930] Configure receive remote notifications with Firebase

- src/wsm/wsm/extensions/Date.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/CreateRequestLeaveViewController.swift
https://dev.framgia.com/redmine/issues/143664
> Fix bug #143664 create leave request

- src/wsm/wsm/viewcontrollers/RequestOff/CreateRequestOffViewController.swift
https://dev.framgia.com/redmine/issues/144927
> [Bug][#144927] Hide day off request type 'has salary, insurance' for unofficial staff

- src/wsm/wsm/api/RequestOtApi/RequestOtApiInputModel.swift
- src/wsm/wsm/model/WorkSpaceShift.swift
https://dev.framgia.com/redmine/issues/143590
> [Bug][#143863] Personal Request : Overtime

- src/wsm/wsm/viewcontrollers/RequestLeave/ListRequestLeaveViewController.swift
https://dev.framgia.com/redmine/issues/144916
> [Bug][#144916] Update ListRequest when create leave request

- src/wsm/wsm.xcodeproj/project.pbxproj
- src/wsm/wsm/NotificationPermission.swift
- src/wsm/wsm/api/NotificationApi/NotificationProvider.swift
- src/wsm/wsm/enums/NotificationTrackableType.swift
- src/wsm/wsm/extensions/UINavigationController.swift
- src/wsm/wsm/model/NotificationModel.swift
- src/wsm/wsm/services/UserServices.swift
- src/wsm/wsm/viewcontrollers/Notification/NotificationViewController.swift
https://dev.framgia.com/redmine/issues/148042
- Add logic for reading all notifications and single notification
> [Task][#148042] Add logic for reading all notifications and single notification

- src/wsm/wsm/viewcontrollers/RequestLeave/CreateRequestLeaveViewController.swift
https://dev.framgia.com/redmine/issues/143707
> [Bug][#143707]Personal request : IL/LE/LO: User have child under 1 years old

- src/wsm/wsm/extensions/UINavigationController.swift
- src/wsm/wsm/viewcontrollers/Notification/NotificationViewController.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/ConfirmCreateRequestLeaveViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOff/ConfirmCreateRequestOffViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOt/ConfirmCreateRequestOtViewController.swift
https://dev.framgia.com/redmine/issues/144926
- Redirect to list OT/leave/day off requests after creating/editing a request.
- Adjust animation when click on a notification.
> [Bug][#144926] Redirect to list leave requests after create new one

- src/wsm/wsm/api/RequestOtApi/RequestOtApiInputModel.swift
- src/wsm/wsm/viewcontrollers/RequestOt/CreateRequestOtViewController.swift
https://dev.framgia.com/redmine/issues/143349
Personal Request	: Overtime: Users is able to submit the form successfully with the company lunch time
> PERSONAL DATA: Personal Request:

- src/wsm/wsm/model/LeaveTypeModel.swift
- src/wsm/wsm/model/WorkSpaceShift.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/CreateRequestLeaveViewController.swift
https://dev.framgia.com/redmine/issues/143851
https://dev.framgia.com/redmine/issues/148508
> [Bug][#143851][#148508] Create Request Woman Only

- src/wsm/wsm/viewcontrollers/TimeSheet/TimeSheetViewController.swift
https://dev.framgia.com/redmine/issues/144109
> [Bug][#144109] Fix bug, refactor code in working calendar screen

- src/wsm/wsm/viewcontrollers/Notification/NotificationViewController.swift
- src/wsm/wsm/viewcontrollers/TimeSheet/TimeSheetViewCell.swift
- src/wsm/wsm/viewcontrollers/TimeSheet/TimeSheetViewController.swift
https://dev.framgia.com/redmine/issues/144361
- Fix comment pull #64
> [Bug][#144361] Set special case N/A timesheet cell to white

- src/wsm/wsm/viewcontrollers/RequestLeave/CreateRequestLeaveViewController.swift
https://dev.framgia.com/redmine/issues/144892
> Bug #144892 [IOS]PERSONAL DATA:IL,LE,LO

- src/wsm/wsm/viewcontrollers/RequestOff/CreateRequestOffViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOff/RequestOffDetailViewController.swift
https://dev.framgia.com/redmine/issues/143732
[IOS] PERSONAL DATA : Personal request : Day Off: "Off no salary" screen should be displayed when the user edit request Off no salary instead of display "Company Pay" screen
> Bug #143732 [IOS] PERSONAL DATA : Personal request :Day Off

- src/wsm/wsm/model/UserProfileModel.swift
- src/wsm/wsm/viewcontrollers/SideMenu/LeftMenuViewController.swift
- src/wsm/wsm/viewcontrollers/TimeSheet/TimeSheetViewController.swift
https://dev.framgia.com/redmine/issues/144348
[iOS] PERSONAL DATA: Working Calendar: Create: Annotation create request off still display for Emp code I/P
> Bug #144348 [iOS] PERSONAL DATA: Working Calendar

- src/wsm/wsm/AppDelegate.swift
- src/wsm/wsm/Base.lproj/Main.storyboard
- src/wsm/wsm/GoogleService-Info.plist
- src/wsm/wsm/api/LoginApi/LoginProvider.swift
- src/wsm/wsm/services/UserServices.swift
- src/wsm/wsm/utils/AlertHelper.swift
- src/wsm/wsm/viewcontrollers/Login/LoginControllerType.swift
- src/wsm/wsm/viewcontrollers/Login/LoginViewController.swift
- src/wsm/wsm/viewcontrollers/SideMenu/LeftMenuViewController.swift
https://dev.framgia.com/redmine/issues/149794
- Add logic to update device token.
- Update login screen (add TPKeyboardAvoiding), update textfield...
- Update GoogleService-Info.plist
> [Task][#149794] Add logic to update device token

- src/wsm/wsm.xcodeproj/project.pbxproj
- src/wsm/wsm/GoogleService-Info.plist
- src/wsm/wsm/Info.plist
- src/wsm/wsm/utils/AppConstant.swift
- src/wsm/wsm/wsm-production.entitlements
https://dev.framgia.com/redmine/issues/149936
> [Task][#149936] Re-configure App ID, Push notification staging

- src/wsm/wsm.xcodeproj/project.pbxproj
- src/wsm/wsm/AppDelegate.swift
- src/wsm/wsm/RemoteNotificationPermission.swift
- src/wsm/wsm/base/BaseViewController.swift
- src/wsm/wsm/extensions/UIViewController.swift
- src/wsm/wsm/utils/Utils.swift
- src/wsm/wsm/viewcontrollers/Notification/NotificationViewController.swift
- src/wsm/wsm/viewcontrollers/Profile/ProfileDetailViewController.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/ConfirmCreateRequestLeaveViewController.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/CreateRequestLeaveViewController.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/ListRequestLeaveViewController.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/RequestLeaveDetailViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOff/ConfirmCreateRequestOffViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOff/CreateRequestOffViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOff/ListRequestOffViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOff/RequestOffDetailViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOt/ConfirmCreateRequestOtViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOt/CreateRequestOtViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOt/ListRequestOtViewController.swift
- src/wsm/wsm/viewcontrollers/RequestOt/OtRequestDetailViewController.swift
- src/wsm/wsm/viewcontrollers/SideMenu/LeftMenuViewController.swift
- src/wsm/wsm/viewcontrollers/TimeSheet/TimeSheetViewController.swift
https://dev.framgia.com/redmine/issues/149951
> [Task][#149951] Add logic when click on a remote notification

- src/wsm/wsm/api/RequestOffApi/ListDayOffSettingApiOutputModel.swift
- src/wsm/wsm/localization/en.lproj/Localizable.strings
- src/wsm/wsm/localization/vi.lproj/Localizable.strings
- src/wsm/wsm/viewcontrollers/RequestOff/CreateRequestOffViewControllerType.swift
https://dev.framgia.com/redmine/issues/143687
> [Bug][#143687] Fix number of annual day off number

- src/wsm/wsm/localization/en.lproj/Localizable.strings
- src/wsm/wsm/localization/vi.lproj/Localizable.strings
- src/wsm/wsm/model/DayOffSettingModel.swift
- src/wsm/wsm/utils/AppConstant.swift
https://dev.framgia.com/redmine/issues/150486
> [Task][#150486] Fix localized string in create request off screen

- src/wsm/wsm/viewcontrollers/TimeSheet/TimeSheetViewCell.swift
- src/wsm/wsm/viewcontrollers/TimeSheet/TimeSheetViewController.swift
https://dev.framgia.com/redmine/issues/144361
> [Bug][#144361] Incorrect color on Timesheet for user in whitelist

- src/wsm/wsm/viewcontrollers/RequestLeave/RequestLeaveDetailViewController.swift
https://dev.framgia.com/redmine/issues/144916
> [Bug][#144916] Auto reload list leave requests after editing

- src/wsm/wsm/viewcontrollers/RequestLeave/CreateRequestLeaveViewController.swift
Link redmine: https://dev.framgia.com/redmine/issues/143680
> [Bug #143680]Create new request:User have child under 6 years old unable submit

- src/wsm/wsm/model/RequestOtModel.swift
- src/wsm/wsm/viewcontrollers/RequestOt/OtRequestDetailViewController.swift
https://dev.framgia.com/redmine/issues/143590
>  [Bug][#143590] Fix number of OT hours in OT request detail screen

- src/wsm/wsm/viewcontrollers/RequestOt/CreateRequestOtViewController.swift
Link redmine: https://dev.framgia.com/redmine/issues/150484
> [Bug #150484] Edit request: Error message fails to display when tap Next

- src/wsm/wsm/viewcontrollers/RequestLeave/CreateRequestLeaveViewController.swift
Link redmine: https://dev.framgia.com/redmine/issues/144884
> [Bug #144884][IOS] PERSONAL DATA:IL,LE,LO:Edit request: "Group" displays incorrectly

- src/wsm/wsm/api/RequestOtApi/RequestOtApiInputModel.swift
https://dev.framgia.com/redmine/issues/150451
>  [Bug][#150451] Allow OT checkin or checkout time in lunch time

- src/wsm/wsm/api/RequestOtApi/RequestOtApiInputModel.swift
- src/wsm/wsm/viewcontrollers/RequestOt/CreateRequestOtViewController.swift
https://dev.framgia.com/redmine/issues/150451
> [Bug][#150451] Remove checking OT time in lunch time

- src/wsm/wsm/api/NotificationApi/NotificationProvider.swift
- src/wsm/wsm/utils/Utils.swift
- src/wsm/wsm/viewcontrollers/Notification/NotificationViewController.swift
- src/wsm/wsm/viewcontrollers/SideMenu/LeftMenuViewController.swift
https://dev.framgia.com/redmine/issues/150608
>  [Bug][#150608] Set application badge number by number of unread notifications

- src/wsm/wsm/viewcontrollers/TimeSheet/TimeSheetSummaryViewCell.swift
link redmine: https://dev.framgia.com/redmine/issues/151191
> [Bug #151191][IOS] Total of Day Off display incorrectly

- src/wsm/wsm/AppDelegate.swift
- src/wsm/wsm/api/NotificationApi/NotificationProvider.swift
- src/wsm/wsm/base/BaseViewController.swift
- src/wsm/wsm/utils/AppConstant.swift
- src/wsm/wsm/viewcontrollers/Notification/NotificationViewController.swift
- src/wsm/wsm/viewcontrollers/SideMenu/LeftMenuViewController.swift
https://dev.framgia.com/redmine/issues/151216
> [Task][#151216] Fix right button badge, add logic, read notification when user tap on

- src/wsm/wsm/Base.lproj/Main.storyboard
- src/wsm/wsm/extensions/UIViewController.swift
- src/wsm/wsm/viewcontrollers/TimeSheet/TimeSheetViewCell.swift
https://dev.framgia.com/redmine/issues/151209
- Hide 'Forgot password' button.
> [Bug][#151209] Update calendar cell for compensation holiday

- src/wsm/wsm/viewcontrollers/ManageRequestListViewController.swift
- src/wsm/wsm/viewcontrollers/ManageRequestListViewController.xib
- src/wsm/wsm/viewcontrollers/ManageRequestTableViewCell.xib
- src/wsm/wsm/viewcontrollers/SideMenu/LeftMenuViewController.swift
- Visible manage request function
- Handle show/hide handle request view
> Feature Accept/Reject Request

- src/wsm/wsm/viewcontrollers/TimeSheet/TimeSheetViewController.swift
link redmine: https://dev.framgia.com/redmine/issues/153483
Effect: ListManage Request
> Bug #153483 [Sprint 7] Time in Filter Request Manager incorrect

- src/wsm/wsm.xcodeproj/project.pbxproj
- src/wsm/wsm/Base.lproj/Main.storyboard
- src/wsm/wsm/interfaces/RequestDetailCell.xib
- src/wsm/wsm/localization/en.lproj/Localizable.strings
- src/wsm/wsm/localization/vi.lproj/Localizable.strings
- src/wsm/wsm/model/CompensationAttribute.swift
- src/wsm/wsm/viewcontrollers/ManageRequestDetailViewController.swift
- src/wsm/wsm/viewcontrollers/ManageRequestDetailViewController.xib
- src/wsm/wsm/viewcontrollers/ManageRequestListViewController.swift
- src/wsm/wsm/viewcontrollers/RequestDetailCell.swift
- src/wsm/wsm/viewcontrollers/RequestLeave/RequestLeaveCell.xib
- src/wsm/wsm/viewcontrollers/UpdateRequestDelegate.swift
- Feature: Manage Request Detail Logic (Fill Data/Approve/Reject)
- Effect: Manage Request List
- Redmine: https://dev.framgia.com/redmine/issues/152343
> Feature #152343 [Sprint 1 - pharse 2] Manage Request List - Fill Data
